import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

const BlogsIndex = ({ blogs }) => {
  console.log(blogs)
  return (
    <>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container flex flex-col  ">
        <h1 className="text-xl tracking-tight">
          Blogs
        </h1>

        <div className="mt-6 space-y-12 lg:grid lg:grid-cols-3 lg:gap-x-6 lg:space-y-0">
          {blogs.map(({ id, attributes: { title, description, image } }) => {
            console.log(image.data.attributes.formats.large.url)
            return (
              <div className="rounded p-3 shadow" key={id}>
                <h1 className="text-xl text-blue-500 underline">
                  <Link href={`/blogs/${id}`}>{title}</Link>
                </h1>
                <h2>{description}</h2>
              </div>
            );
          })}
        </div>
      </div>
    </>
  );
};

export default BlogsIndex;

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch("http://localhost:1337/api/blogs?populate=*");
  const data = await res.json();

  // Pass data to the page via props
  return { props: { blogs: data.data } };
}
