{% for domain in domains %}
stage: 1
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '{{ domain.domain_md5 }}'
  namespace: '{{ namespace }}'
spec:
  dnsNames:
  - '{{ domain.domain_md5 }}.parallax.dev'
  - '{{ domain.domain }}'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: '{{ domain.domain_md5 }}-ssl'
---
{% endfor %}