import Head from "next/head";
import moment from "moment";

const BlogsIndex = ({
  blog: {
    attributes: { title, author, content, createdAt },
  },
}) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white pt-8 pb-16 dark:bg-gray-900 dark:text-white lg:pt-16 lg:pb-24">
        <div className="mx-auto flex max-w-screen-xl justify-between px-4 ">
          <article className="format format-sm sm:format-base lg:format-lg format-blue dark:format-invert mx-auto w-full max-w-2xl">
            <header className="not-format mb-4 lg:mb-6">
              <address className="mb-6 flex items-center not-italic">
                <div className="mr-3 inline-flex items-center text-sm text-gray-900 dark:text-white">
                  <div>
                    <span className="text-xl font-bold text-gray-900 dark:text-white">
                      {author}
                    </span>
                    <p className="text-base font-light text-gray-500 dark:text-gray-400">
                      {moment(createdAt).format("MM/DD/YYYY")}
                    </p>
                  </div>
                </div>
              </address>
              <h1 className="mb-4 text-3xl font-extrabold leading-tight text-gray-900 dark:text-white lg:mb-6 lg:text-4xl">
                {title}
              </h1>
            </header>
            <div>{content}</div>
          </article>
        </div>
      </main>
    </>
  );
};

export default BlogsIndex;

export async function getServerSideProps(context: { params: { id: any } }) {
  const { id } = context.params; // Use `context.params` to get dynamic params
  const res = await fetch(`http://localhost:1337/api/blogs/${id}?populate=*`);
  const blog = await res.json();

  return { props: { blog: blog.data } };
}
